### ISSUE TITLE
How to make stream audio?

### ISSUE THREAD

**Issue by orewafuad** [ybd-project-ver1/ytdl-core#21]
## Describe the feature

how to make stream audio?

**Comment by ybd-project-ver1** [comment]
Please refer to this
https://github.com/ybd-project-ver1/ytdl-core/tree/latest/examples%2FDefault%2FStreamResponse

**Comment by ybd-project-ver1** [comment]
Do you want to use a pipeable stream or a regular ReadableStream?

**Comment by orewafuad** [comment]
> Do you want to use a pipeable stream or a regular ReadableStream?

pipeable stream, i tried from the example but return error "sign in you're not bot"

**Comment by ybd-project-ver1** [comment]
Can you send me the code you are implementing?
The bot error could be improved by changing the IP or implementing Cloudflare Workers own proxy. Please ask me for more details.

**Comment by orewafuad** [comment]
I implement code base on example
```
const express = require('express'),
    { YtdlCore } = require('@ybd-project/ytdl-core'),
    app = express(),
    ytdl = new YtdlCore({
        hl: 'en',
        gl: 'US',
        streamType: 'nodejs',
    });

app.get('/api/download/audio', (req, res) => {
    const VIDEO_ID = req.query.videoId;

    res.setHeader('Content-Type', 'audio/mp3');
    res.setHeader('Content-Disposition', 'attachment; filename="audio.mp3"');

    ytdl.download(`https://www.youtube.com/watch?v=${VIDEO_ID}`, {
        filter: 'audioonly',
    })
        .then((stream) => {
            stream.pipe(res);
        })
        .catch((err) => {
            res.json({
                error: err.message,
            });
        });
});
```

**Comment by ybd-project-ver1** [comment]
Since you say you are getting bot errors, try using your own proxy. An example implementation can be found in examples/Default/OriginalProxy.

**Comment by orewafuad** [comment]
And just copy & paste the example code to cloudflare workers?

**Comment by ybd-project-ver1** [comment]
yes

**Comment by orewafuad** [comment]
i was implementing using originalProxy, but it gave me an error: 'Unhandled Rejection: RequestError: Status Code: 400'.

**Comment by ybd-project-ver1** [comment]
Can you provide a complete debug log?

**Comment by orewafuad** [comment]
Unhandled Rejection: RequestError: Status Code: 400
    at Fetcher.request (/var/task/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:860:119949)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getHtml5Player (/var/task/node_modules/@ybd-project/ytdl-core/bundle/node.cjs:873:1243) {
  statusCode: 400
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.

**Comment by orewafuad** [comment]
```
 const ytdl = new YtdlCore({
      originalProxy: {
       base: 'https://lively-unit-fec6.nsfuad5.workers.dev/',
         download: 'https://lively-unit-fec6.nsfuad5.workers.dev/video-download',
      urlQueryName: 'apiUrl',
  },
 });
```
my code

**Comment by ybd-project-ver1** [comment]
This is a bug in ytdl-core. The value of `urlQueryName` is not adapted correctly and 400 is responded. This will be fixed in the next version. The current solution is to change the query name from `apiUrl` to `url`.

**Comment by orewafuad** [comment]
> Change `urlQueryName` from `apiUrl` to `url`.
> 
> In addition, have you made any changes to this API?

no

**Comment by orewafuad** [comment]
When I tried to access my CF worker, I got the error 'This page isn’t working right now.' Is that expected?

**Comment by orewafuad** [comment]
before it's working, but now i got an error .
"throw new Error(`No such format found: ${QUALITY}`);
                  ^
Error: No such format found: highest"

**Comment by ybd-project-ver1** [comment]
Can you provide a complete debug log?
To output debug logs, specify `logDisplay: [“debug”]` as an option when creating an instance.

```ts
import { YtdlCore } from '@ybd-project/ytdl-core';

const ytdl = new YtdlCore({
    logDisplay: ["debug"]
});
```

**Comment by orewafuad** [comment]
[  DEBUG  ]: [ web ]: Success
[  DEBUG  ]: [ webCreator ]: Error
Reason: Please sign in
[  DEBUG  ]: [ tvEmbedded ]: Error
Reason: Please sign in
[  DEBUG  ]: [ ios ]: Success
[  DEBUG  ]: [ android ]: Error
Reason: This video is unavailable
[  DEBUG  ]: [ webEmbedded ]: Success
[  DEBUG  ]: [ tv ]: Success
[  DEBUG  ]: [ mweb ]: Success
[  DEBUG  ]: [ web ]: Success
[  DEBUG  ]: [ FileCache ]: Cache key "decipherFunction" was available.
[  DEBUG  ]: [ FileCache ]: Cache key "nTransformFunction" was available.
[  DEBUG  ]: [ web ]: The URL for the video did not return a successful response. Got another format.
Reason: Status code: 403
[  DEBUG  ]: [ ios ]: The URL for the video did not return a successful response. Got another format.
Reason: Status code: 403

**Comment by ybd-project-ver1** [comment]
Please install v6.0.5 and see if this problem has been resolved. Note that the 403 problem is a very difficult one and may be difficult to remedy.

**Comment by orewafuad** [comment]
![Screenshot_103](https://github.com/user-attachments/assets/eb3a0728-c569-44bb-b127-8460c41a6c09)
i got this error

**Comment by ybd-project-ver1** [comment]
> i got this error

What codes are you using?

**Comment by orewafuad** [comment]
Copying from the example bro, but now i don't know why i'm getting `ReadableStream is not defined`

**Comment by ybd-project-ver1** [comment]
Is this “ReadableStream is not defined” occurring on the CF Worker?
Or is it on the server running ytdl-core? To confirm the error, you may not be using a pipable stream.

**Comment by orewafuad** [comment]
I don't know. When I tried upgrading to 6.0.5, I suddenly got the error 'ReadableStream is not defined.' When I went back to 6.0.4, the issue was still there. I'm using Glitch, by the way.

**Comment by ybd-project-ver1** [comment]
The problem with ReadableStream not being defined is due to an older version of Node.js in the case of Glitch. Please use at least Node.js v16 or higher. Also, what code are you importing YtdlCore? (Please give me code like this)
```ts
import { YtdlCore } from '@ybd-project/ytdl-core';
```

**Comment by orewafuad** [comment]
I just type `import { YtdlCore } from '@ybd-project/ytdl-core';` and give me error readablestream is not defined

![Screenshot_20241030_154645_Chrome](https://github.com/user-attachments/assets/9837d81d-03e1-418c-ada6-7aaba36d4dbe)

**Comment by ybd-project-ver1** [comment]
Sorry for the delay in replying, but when using Glitch I often get errors. Basically, we have implemented it so that it works with Glitch, but maybe it doesn't.
I will investigate.

**Comment by orewafuad** [comment]
I updated to version 6.0.6, but I’m still facing the issue: `TypeError: stream.on is not a function.`

**Comment by orewafuad** [comment]
![Screenshot_20241110_102754_Chrome](https://github.com/user-attachments/assets/64396474-a2af-4baf-8486-72a1c97829c8)

**Comment by ybd-project-ver1** [comment]
Version 6.0.6 has a bug, please install 6.0.6-2.

**Comment by orewafuad** [comment]
Still error

**Comment by ybd-project-ver1** [comment]
What is the code you are implementing?

**Comment by orewafuad** [comment]
```
import { YtdlCore } from '@ybd-project/ytdl-core';
const ytdl = new YtdlCore({
       originalProxy: {
        base: urlproxy,
        download: urlproxy/download,
        urlQueryName: 'url',
    },
  logDisplay: ["debug", "info", "success", "warning", "error"],
  clients:  ['web', 'webCreator', 'webEmbedded', 'android', 'ios', 'tv', 'tvEmbedded', 'mweb']
});
```

**Comment by ybd-project-ver1** [comment]
There seems to be no problem with the code.
What errors are you seeing?

**Comment by fsholehan** [comment]
> ![Screenshot_20241110_102754_Chrome](https://private-user-images.githubusercontent.com/121205011/384656331-64396474-a2af-4baf-8486-72a1c97829c8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMTI1MjgsIm5iZiI6MTczMTMxMjIyOCwicGF0aCI6Ii8xMjEyMDUwMTEvMzg0NjU2MzMxLTY0Mzk2NDc0LWEyYWYtNGJhZi04NDg2LTcyYTFjOTc4MjljOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwODAzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDBkYjY1ZWVjZDhkZTRiNWE0NDdlYTBhMjcwMzJkNTcwODcxM2E1NWVmNDc5ZDI2NzNmZDA5NTg3Mzc3ZWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7h19UecBSv45bntpAT656t37eL_nwgIj8NF581pZjrY)

This

**Comment by orewafuad** [comment]
![Screenshot_108](https://github.com/user-attachments/assets/354f6334-7bbf-4b2f-8c75-d22e389eab86)
also getting error when in local

**Comment by ybd-project-ver1** [comment]
> > I updated to version 6.0.6, but I’m still facing the issue: `TypeError: stream.on is not a function.`
> 
> This

What is the code for where you are using `stream.on`?

**Comment by orewafuad** [comment]
> > > I updated to version 6.0.6, but I’m still facing the issue: `TypeError: stream.on is not a function.`
> > 
> > 
> > This
> 
> What is the code for where you are using `stream.on`?

Nothing, I just imported the ytdl package and got the error.

**Comment by fsholehan** [comment]
The error is actually `ReferenceError: ReadableStream is not defined`. You can check the full code here. [music-youtube](https://github.com/[fsholehan/music-youtube](https://github.com/fsholehan/music-youtube/tree/main)/tree/main)

**Comment by ybd-project-ver1** [comment]
> The error is actually `ReferenceError: ReadableStream is not defined`. You can check the full code here. https://github.com/fsholehan/music-youtube

Errors related to `ReadableStream` are most likely a problem with the version of Node.js or environment in which the app is running. What version of Node.js are you using?

**Comment by ybd-project-ver1** [comment]
> Nothing, I just imported the ytdl package and got the error.

The code `stream.on` is not implemented in ytdl-core and such an error is not expected to occur.
If you are migrating from @distube/ytdl-core or similar to @ybd-project/ytdl-core, you need to change your code.

**Comment by orewafuad** [comment]
> > The error is actually `ReferenceError: ReadableStream is not defined`. You can check the full code here. https://github.com/fsholehan/music-youtube
> 
> Errors related to `ReadableStream` are most likely a problem with the version of Node.js or environment in which the app is running. What version of Node.js are you using?
On Glitch, I set Node.js to 16.x. The `ReadableStream` issue appears from version 6.0.5 and higher, but there’s no problem with version 6.0.4.

**Comment by orewafuad** [comment]
> > Nothing, I just imported the ytdl package and got the error.
> 
> The code `stream.on` is not implemented in ytdl-core and such an error is not expected to occur. If you are migrating from @distube/ytdl-core or similar to @ybd-project/ytdl-core, you need to change your code.

On my new project only implements your package, but get same error.

**Comment by ybd-project-ver1** [comment]
The spam flag on ybd-project's account has been lifted, so you can resume discussion from here.
Please note that this repository (account) will be removed after 24 hours.

**Comment by orewafuad** [comment]
I think the problem is undici version
